Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -46,10 +46,10 @@ jobs:
 
           echo "Pull latest image"
           docker pull $IMAGE
-
+          
           echo "Check current running container"
           CURRENT=$(docker ps --filter "name=userauthsystem" --format "{{.Names}}")
-
+          
           if [ "$CURRENT" == "userauthsystem-blue" ]; then
             NEW="userauthsystem-green"
             OLD="userauthsystem-blue"
@@ -59,25 +59,37 @@ jobs:
             OLD="userauthsystem-green"
             PORT=8081
           fi
-
+          
+          echo "Free port if already used"
+          docker ps -q --filter "publish=$PORT" | xargs -r docker stop
+          docker ps -aq --filter "publish=$PORT" | xargs -r docker rm
+          
           echo "Starting new container: $NEW on port $PORT"
           docker run -d --name $NEW -p $PORT:8080 $IMAGE
-
+          
+          #IMPORTANT: CHECK IF CONTAINER STARTED
+          RUNNING=$(docker ps --filter "name=$NEW" --format "{{.Names}}")
+          
+          if [ "$RUNNING" != "$NEW" ]; then
+            echo "Container failed to start"
+            exit 1
+          fi
+          
           echo "Waiting for app to be ready..."
           sleep 20
-
+          
           echo "Health check..."
           curl -f http://localhost:$PORT/actuator/health || exit 1
-
+          
           echo "Switching Nginx to port $PORT"
           sudo sed -i "s/server 127.0.0.1:.*/server 127.0.0.1:$PORT;/" /etc/nginx/conf.d/upstream.conf
-
+          
           sudo nginx -t
           sudo systemctl reload nginx
-
+          
           echo "Stopping old container: $OLD"
           docker stop $OLD || true
           docker rm $OLD || true
-
+          
           echo "Cleanup old images"
           docker image prune -af
